export default {
  content: ["./src/**/*.{astro,html,js,jsx,ts,tsx,vue,svelte,md,mdx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#ffffff",
        "surface-container": "#f8f9fa",
        "surface-container-low": "#fcfcfc",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#f1f3f4",
        "surface-container-highest": "#e1e3e4",
        "surface-bright": "#ffffff",
        "surface-dim": "#d9dadb",
        "surface-variant": "#e1e3e4",
        background: "#ffffff",
        primary: "#1A36B0",
        "primary-container": "#1a36b0",
        "primary-fixed": "#dee0ff",
        "primary-fixed-dim": "#bac3ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#a0aeff",
        "on-primary-fixed": "#00115a",
        "on-primary-fixed-variant": "#1c38b1",
        secondary: "#515d84",
        "secondary-container": "#c4d0fd",
        "secondary-fixed": "#dbe1ff",
        "secondary-fixed-dim": "#b9c5f2",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#4c587f",
        "on-secondary-fixed": "#0b1a3d",
        "on-secondary-fixed-variant": "#39456b",
        tertiary: "#001e8e",
        "tertiary-container": "#002ec7",
        "tertiary-fixed": "#dee0ff",
        "tertiary-fixed-dim": "#bac3ff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#a1aeff",
        "on-tertiary-fixed": "#00105b",
        "on-tertiary-fixed-variant": "#002eca",
        "on-surface": "#191c1d",
        "on-surface-variant": "#444654",
        "on-background": "#191c1d",
        outline: "#757685",
        "outline-variant": "#c5c5d6",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f2",
        "inverse-primary": "#bac3ff",
        "surface-tint": "#3a52ca",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Manrope"],
        label: ["Manrope"],
      },
      fontWeight: {
        bold: "500",
        extrabold: "500",
        semibold: "500",
        medium: "500",
      },
    },
  },
};
